# Generated by Django 5.0 on 2023-12-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='decription',
            new_name='description',
        ),
    ]
